export enum Icons {
  Github = "github",
  Search = "search",
  QueueMusic = "queue-music",
  Favorite = "favorite",
  Live = "live",
  Download = "download",
  Mobile = "mobile",
  Offline = "offline",
  Android = "android",
  Security = "security",
  Code = "code",
  Backup = "backup",
  Design = "design",
  Language = "language",
  LinkedIn = "linkedin",
  Twitter = "twitter",
  Email = "email",
  CarConnected = "car-connected",
  Sun = "sun",
}
